import { Hono } from "hono";
import type { Env, Variables } from "../env";
import { jsonError, ErrorCode } from "../lib/errors";
import { log } from "../lib/log";
import { createLiteOpenAiSession, liveAvatarApiKey, stopLiveAvatarSession } from "../lib/liveavatar";
import { insertRow } from "../lib/d1-helpers";
import { ensureOperationalSchema } from "../lib/ensure-schema";
import { requireAuth } from "../lib/auth-middleware";
import { requireTier } from "../lib/tier";

export const avatarRoutes = new Hono<{ Bindings: Env; Variables: Variables }>();

avatarRoutes.post("/session", requireAuth, requireTier("pro"), async (c) => {
  await ensureOperationalSchema(c.env.DB);
  if (!liveAvatarApiKey(c.env)) {
    return jsonError(
      c,
      503,
      ErrorCode.Upstream,
      "LiveAvatar API key is not configured.",
      "HUMAN ACTION REQUIRED — wrangler secret put HEYGEN_API_KEY --config workers/api/wrangler.prod.toml",
    );
  }
  if (!c.env.OPENAI_API_KEY && !c.env.LIVEAVATAR_OPENAI_SECRET_ID) {
    return jsonError(
      c,
      503,
      ErrorCode.Upstream,
      "OpenAI Realtime is not configured for LiveAvatar.",
      "HUMAN ACTION REQUIRED — wrangler secret put OPENAI_API_KEY --config workers/api/wrangler.prod.toml",
    );
  }

  const body = (await c.req.json().catch(() => ({}))) as {
    agentType?: string;
    language?: string;
    sandbox?: boolean;
  };
  const customerId = Number(c.get("customerId") ?? c.get("userId"));

  try {
    const session = await createLiteOpenAiSession(c.env, body);
    if (Number.isInteger(customerId) && customerId > 0) {
      await insertRow(c.env.DB, "avatar_sessions", {
        customer_id: customerId,
        live_session_id: session.sessionId,
        provider: session.provider,
        mode: session.mode,
        status: "started",
      }).catch(() => 0);
    }
    log.info("liveavatar_session_started", {
      requestId: c.get("requestId"),
      sandbox: session.sandbox,
    });
    return c.json({
      provider: "heygen",
      mode: session.mode,
      engine: "openai-realtime",
      sessionId: session.sessionId,
      sessionToken: session.sessionToken,
      livekitUrl: session.livekitUrl,
      livekitClientToken: session.livekitClientToken,
      avatarName: session.avatarName,
      sandbox: session.sandbox,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log.error("liveavatar_session_error", { err: message });
    return jsonError(c, 502, ErrorCode.Upstream, "Unable to start a LiveAvatar session.");
  }
});

avatarRoutes.post("/session/stop", async (c) => {
  const body = (await c.req.json().catch(() => ({}))) as { sessionToken?: string };
  if (body.sessionToken) await stopLiveAvatarSession(body.sessionToken);
  return c.json({ ok: true });
});

avatarRoutes.post("/session/sdp", async (c) =>
  jsonError(c, 410, ErrorCode.Gone, "D-ID WebRTC is no longer used. Connect via LiveAvatar LiveKit."),
);

avatarRoutes.post("/session/ice", async (c) =>
  jsonError(c, 410, ErrorCode.Gone, "D-ID WebRTC is no longer used. Connect via LiveAvatar LiveKit."),
);

avatarRoutes.post("/speak", async (c) =>
  jsonError(
    c,
    410,
    ErrorCode.Gone,
    "Avatar speech is generated by OpenAI Realtime. Do not send TTS to the deprecated speak API.",
  ),
);

avatarRoutes.get("/available", async (c) =>
  c.json({
    provider: "liveavatar-openai",
    mode: "LITE",
    configured: Boolean(liveAvatarApiKey(c.env) && (c.env.OPENAI_API_KEY || c.env.LIVEAVATAR_OPENAI_SECRET_ID)),
  }),
);
